### ISSUE TITLE
User stories - Improve TrailGage App

### ISSUE THREAD

**Issue by alynnka** [DIT112-V20/group-11#14]
**Description**

- As a developer I want to constantly improve the App so that we gain trust from the final user.

**Comment by platisd** [comment]
This is **not** an [INVEST](https://www.agilealliance.org/glossary/invest/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'invest))~searchTerm~'~sort~false~sortDirection~'asc~page~1)) user story.
